### ISSUE TITLE
Clipboard in code examples should appear on hover only

### ISSUE THREAD

**Issue by dalexsy** [mdn/bob#582]
Could we change how the clipboard extension works for the code examples? Right now, the clipboard is always visible on the focused code example. 

![clipboard](https://user-images.githubusercontent.com/44966503/122931465-36401f00-d36d-11eb-9275-83d13a17b6ab.gif)

If I want to copy an example that isn't focused, I would go to highlight the text, which also switches the focus in the example on mouse up. I think it would make more sense if the clipboard is only visible when hovering over an example so when users are going to select something to copy it, they'd see the clipboard instead. It also would cut down on the visual noise in the examples if the clipboard is only shown when the user would need it.

cc: @tannerdolby

**Comment by tannerdolby** [comment]
I like the combination of the `.example-choice` hover state border paired with the clippy icon being displayed on hover, it looks quite nice. Also, the visual noise is reduced by having the clippy button only show when the example choice is hovered. For the JS portion, I tried not to change any methods in `clippy.js` and created a `handleExampleHover` local function in `editable-css.js` to handle any hiding/showing work for the clippy button when example choices are hovered. 

Since `clippy.toggleClippy()` usage already handles setting `aria-hidden` attributes for each example choices clippy button as well as adding the `.hidden` class, there wasn't much to add other than to attach some mouse event handlers to each example choice to ensure the `.copy` button had the proper `aria-hidden` values and was visible for all users when it was supposed to be.

Below is a quick demo, I'm tabbing to the clippy icon but clicking on it would work the same way. I wanted to make sure that when a example choice was hovered, the clippy icon would appear next in the tab order after the editable `<code>`. 



https://user-images.githubusercontent.com/48612525/123148315-eddc3c00-d414-11eb-8b13-25665de55bb3.mov

**Comment by schalkneethling** [comment]
I am thinking we can reach a compromise based on how we did it for the other copy to clipboard code examples i.e.

1. Have it at a lower opacity be default as an indication that you can easily copy the example
2. On hover or keyboard focus(on desktop) make it opaque 
3. Have it as is on mobile as there is no hover state

Thoughts @dalexsy @tannerdolby

**Comment by dalexsy** [comment]
@tannerdolby I think that looks great. That's exactly what I was thinking.

@schalkneethling I still think I wouldn't always show it because in the example shown, you would have three icons, which draws focus from the code examples. Other sites often show the icon on hover only because users are already performing the steps it would take to copy something, so they're going to hover over the text at some point.

Examples where the copy button is persisted:
https://stripe.com/docs/api/pagination/auto
https://angular.io/guide/reactive-forms
https://docs.microsoft.com/en-us/previous-versions/dotnet/framework/install/on-windows-7

The difference with the persisted examples is they only have standalone code blocks. We have the code and the compiled example next to it, which is just a lot more information. I would still recommend we only show it on hover, and even then with the subtler pre-hover state I think it had when it fist was added it and only make it full contrast one the user hovers over the icon itself.

I have to revisit the code examples as part of the redesign anyway, but for now I think what @tannerdolby's added here is the best solution for now. I also found the persistent lower contrast icons it had before overwhelming.

**Comment by dalexsy** [comment]
Oh ha, I've had the [border-block](https://developer.mozilla.org/en-US/docs/Web/CSS/border-block) page open all week and only just now scrolled down to see the standalone code blocks. It's great to have the clipboard persisted for these sections, but yeah, we still probably shouldn't show it on the interactive examples.

**Comment by tannerdolby** [comment]
> I am thinking we can reach a compromise based on how we did it for the other copy to clipboard code examples i.e.

My thoughts are that it would be OK to have the clippy icon use the same styles applied for the standalone code blocks (ie low opacity initial state and transitions to fully opaque upon hover/focus). I think keeping it as is on mobile would be ideal as there isn't hover state just touch/click happening. With that said, I do agree with @dalexsy that having an icon for all three of example choices does take focus away a small bit from the code within the choices themselves. 

If we could use number 3 in your list @schalkneethling and instead of having lower opacity and moving to fully opaque in number 1, just have it `display: none` or more accessibly hidden initially, then upon hover/focus state of the `<code>` within the example choice or even the `.example-choice` div itself trigger the clippy icon to display and be visible to assistive technologies with the correct `aria-hidden` attribute.

**Comment by tannerdolby** [comment]
> I still think I wouldn't always show it because in the example shown, you would have three icons, which draws focus from the code examples

I think I'm feeling the same about this. Having the three clippy icons visible in each example initially looks good, but it does introduce quite a bit of extra "stuff" for my eyes to jump around at when I should be focused on the initial choice selected and its corresponding code relative to the output on the right. 

If we keep the icon hidden initially for each choice, I can much more quickly visually scan top-down the example choices (no mouse) without even thinking about copy-to-clipboard, then when I feel ready to take a "deeper" look and see what that specific example choice does, I can mouseover or focus it (which will display the clippy icon) for that example and checkout the code and see the output on right. I think this sort of implementation is much less overwhelming from a reader viewpoint, and provides a way to make each example choice easier to visually focus on while changing choices whilst only thinking about copy/paste when your focused or have selected an example choice which then the clippy icon appears.

**Comment by schalkneethling** [comment]
@tannerdolby and @dalexsy - I reckon it is a good idea to tackle this holistically as part of the redesign so we can create this cohesive experience.

FYI @tannerdolby - Everyone at Mozilla is out this week as Mozilla is closed for a wellness week. Expect slow or no response as a result. All back to work next week ~Tuesday-ish due to 4th of July being observed on the 5th I believe.

**Comment by tannerdolby** [comment]
> @tannerdolby and @dalexsy - I reckon it is a good idea to tackle this holistically as part of the redesign so we can create this cohesive experience.

Ok sounds like a plan to me! @schalkneethling 

> FYI @tannerdolby - Everyone at Mozilla is out this week as Mozilla is closed for a wellness week. Expect slow or no response as a result. All back to work next week ~Tuesday-ish due to 4th of July being observed on the 5th I believe.

Ahh ok that makes sense, I was wondering where everybody was 😄 thank you for the heads up! 

Enjoy your 4th of July and the rest of your time off! 🎆
