### ISSUE TITLE
Update color palette

### ISSUE THREAD

**Issue by schalkneethling** [mdn/bob#738]
Update the color palette here to match the updated palette used in Yari.

**Comment by djfarly** [comment]
Hej - this issue seems appropriate for what I found.

CSS Variables (`.cm-variable-2`) have very poor color contrast in dark mode.

<img width="241" alt="Screenshot 2022-03-31 at 09 14 03" src="https://user-images.githubusercontent.com/5230863/160998928-788a32ac-bd7e-4bae-b7eb-718cb1c6c737.png">
<img width="373" alt="Screenshot 2022-03-31 at 09 13 45" src="https://user-images.githubusercontent.com/5230863/160998933-860be759-1cbe-4aca-b714-b3654284b33c.png">

Peace :)

**Comment by schalkneethling** [comment]
Agreed, thanks @djfarly.
