### ISSUE TITLE
Is auto-deployment of new/updated example pages broken?

### ISSUE THREAD

**Issue by wbamberg** [mdn/bob#913]
See https://github.com/mdn/content/pull/21202 - we've had several occasions lately where a contributor has added an `EmbedInteractiveExample` call to add a new interactive example, but the example is 404. We ask @schalkneethling to kick the deploy process off and this seems to resolve it. But these things used to be built automatically, has something changed/broken?

See also for instance https://github.com/mdn/interactive-examples/pull/2279 which updated the examples for [`<hgroup>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup) more than a week ago, but the page is still showing the old example.

**Comment by rubiesonthesky** [comment]
About interactive examples, for me it seems this auto release is broken https://github.com/mdn/interactive-examples/pull/2290 that changelog does not have all changes since 1.0.2. 

That one github action https://github.com/mdn/content/pull/21334 has update with breaking change. It broke asome actions in other mdn repositories. I wonder could it be cause here too?

**Comment by rubiesonthesky** [comment]
https://github.com/mdn/bob/actions/runs/3171243243/jobs/5164495076

Not sure if this related either, but that release please action expects repository to use conventional commits and since this repo does not use them always, it does not find any "user facing commits". Though I did not go through the history if there is some fix or feat commits.

> Release Please creates a release pull request after it notices the default branch contains "releasable units" since the last release. A releasable unit is a commit to the branch with one of the following prefixes: "feat", "fix", and "deps". (A "chore" or "build" commit is not a releasable unit.)

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/interactive-examples/pull/2337.
